# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{puret}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Johannes Jorg Schmidt"]
  s.date = %q{2011-08-04}
  s.description = %q{Pure model translations}
  s.email = %q{schmidt@netzmerk.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "init.rb",
    "lib/generators/puret.rb",
    "lib/generators/puret/attribute/attribute_generator.rb",
    "lib/generators/puret/attribute/templates/migration.rb",
    "lib/generators/puret/model/model_generator.rb",
    "lib/generators/puret/model/templates/migration.rb",
    "lib/generators/puret/model/templates/model.rb",
    "lib/puret.rb",
    "lib/puret/active_record_extensions.rb",
    "lib/puret/version.rb"
  ]
  s.homepage = %q{http://github.com/jo/puret}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Pure model translations}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

